### ISSUE TITLE
Issue with payu_upi_flutter version 0.0.2, but 0.0.1 works fine

### ISSUE THREAD

**Issue by himanshujjp** [payu-intrepos/PayU-UPI-Flutter#1]
I'm encountering an issue with the payu_upi_flutter package after upgrading from version 0.0.1 to 0.0.2. My app works as expected with 0.0.1, but when I try to use 0.0.2, I run into the following problem(s):

Steps to fix:
Add payu_upi_flutter: 0.0.1 to pubspec.yaml.
Run flutter clean.
Run flutter pub get.
Try to build and run the app.

**Comment by shahfaizalc** [comment]
@himanshujjp  what is the error you get. kindly reach out to mobile.integration@payu.in
